import { Event, User } from '../types';

// Mock users
export const mockUsers: User[] = [
  {
    id: 'user1',
    username: 'aaronjin',
    displayName: 'Aaron Jin',
    isOrganization: false,
    profileImageUrl: 'https://randomuser.me/api/portraits/lego/1.jpg',
    userType: 'student',
  },
  {
    id: 'org1',
    username: 'stanfordpoker',
    displayName: 'Stanford Poker',
    isOrganization: true,
    profileImageUrl: 'https://logo.clearbit.com/stanford.edu',
    userType: 'organization',
  },
  {
    id: 'org2',
    username: 'ksa',
    displayName: 'Korean Students Association',
    isOrganization: true,
    profileImageUrl: 'https://logo.clearbit.com/stanford.edu',
    userType: 'organization',
  },
  {
    id: 'org3',
    username: 'sigmachi',
    displayName: 'Sigma Chi',
    isOrganization: true,
    profileImageUrl: 'https://logo.clearbit.com/stanford.edu',
    userType: 'organization',
  },
];

// Mock events
export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Free Pizza Night',
    description: 'Come join us for free pizza and networking with fellow Stanford students!',
    organizerId: 'org1',
    organizerName: 'Stanford Eats',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Tressider Union',
    dateTime: '2025-05-15T18:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
    isPrivate: false,
    pullUpCount: 125,
    userPulledUp: true,
    eventPassword: undefined,
    created_at: String(Math.floor(Date.now() / 1000) - 86400), // 1 day ago
  },
  {
    id: 'event2',
    title: 'Acappella Spring Concert',
    description: 'Join us for our annual spring concert featuring all Stanford acappella groups!',
    organizerId: 'org2',
    organizerName: 'Stanford Mendicants',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Memorial Auditorium',
    dateTime: '2025-05-20T19:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81',
    isPrivate: false,
    pullUpCount: 87,
    userPulledUp: false,
    eventPassword: undefined,
    created_at: String(Math.floor(Date.now() / 1000) - 172800), // 2 days ago
  },
  {
    id: 'event3',
    title: 'Private Mixer',
    description: 'Exclusive mixer for members and invited guests only.',
    organizerId: 'org3',
    organizerName: 'Stanford Sigma Chi',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Greek Row',
    dateTime: '2025-05-21T21:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1496024840928-4c417adf211d',
    isPrivate: true,
    pullUpCount: 45,
    userPulledUp: false,
    eventPassword: 'MIXER2025',
    created_at: String(Math.floor(Date.now() / 1000) - 259200), // 3 days ago
  },
  {
    id: 'event4',
    title: 'Tech Talk: AI in Healthcare',
    description: 'Learn about the latest applications of AI in healthcare from industry experts.',
    organizerId: 'org1',
    organizerName: 'Stanford Healthcare Consulting Group',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Engineering Quad',
    dateTime: '2025-05-25T17:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef',
    isPrivate: false,
    pullUpCount: 62,
    userPulledUp: false,
    eventPassword: undefined,
    created_at: String(Math.floor(Date.now() / 1000) - 43200), // 12 hours ago
  },
  {
    id: 'event5',
    title: 'Spring Game Day',
    description: 'Join us for a day of games, food, and fun! All students welcome.',
    organizerId: 'org3',
    organizerName: 'Stanford Kappa Sigma',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Main Quad',
    dateTime: '2025-05-27T14:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-c70f1b34e2e7',
    isPrivate: false,
    pullUpCount: 94,
    userPulledUp: true,
    eventPassword: undefined,
    created_at: String(Math.floor(Date.now() / 1000) - 3600), // 1 hour ago
  },
]; 