import { Event, Comment, User } from '../types';

// Mock users
export const mockUsers: User[] = [
  {
    id: 'user1',
    username: 'aaronjin',
    displayName: 'Aaron Jin',
    isOrganization: false,
    profileImageUrl: 'https://randomuser.me/api/portraits/lego/1.jpg',
  },
  {
    id: 'org1',
    username: 'stanfordpoker',
    displayName: 'Stanford Poker',
    isOrganization: true,
    profileImageUrl: 'https://logo.clearbit.com/stanford.edu',
  },
  {
    id: 'org2',
    username: 'ksa',
    displayName: 'Korean Students Association',
    isOrganization: true,
    profileImageUrl: 'https://logo.clearbit.com/stanford.edu',
  },
  {
    id: 'org3',
    username: 'sigmachi',
    displayName: 'Sigma Chi',
    isOrganization: true,
    profileImageUrl: 'https://logo.clearbit.com/stanford.edu',
  },
];

// Mock events
export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Free Pizza Night',
    description: 'Come join us for free pizza and networking with fellow Stanford students!',
    organizerId: 'org1',
    organizerName: 'Stanford Eats',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Tressider Union',
    dateTime: '2023-05-15T18:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
    category: 'Food',
    isPrivate: false,
    upvotes: 125,
    downvotes: 5,
    userVote: 'up',
    saved: true,
  },
  {
    id: 'event2',
    title: 'Acappella Spring Concert',
    description: 'Join us for our annual spring concert featuring all Stanford acappella groups!',
    organizerId: 'org2',
    organizerName: 'Stanford Mendicants',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Memorial Auditorium',
    dateTime: '2023-05-20T19:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81',
    category: 'Music',
    isPrivate: false,
    upvotes: 87,
    downvotes: 3,
    userVote: null,
    saved: false,
  },
  {
    id: 'event3',
    title: 'Private Mixer',
    description: 'Exclusive mixer for members and invited guests only.',
    organizerId: 'org3',
    organizerName: 'Stanford Sigma Chi',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Greek Row',
    dateTime: '2023-05-21T21:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1496024840928-4c417adf211d',
    category: 'Social',
    isPrivate: true,
    upvotes: 45,
    downvotes: 2,
    userVote: null,
    saved: false,
  },
  {
    id: 'event4',
    title: 'Tech Talk: AI in Healthcare',
    description: 'Learn about the latest applications of AI in healthcare from industry experts.',
    organizerId: 'org1',
    organizerName: 'Stanford Healthcare Consulting Group',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Engineering Quad',
    dateTime: '2023-05-25T17:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef',
    category: 'Academic',
    isPrivate: false,
    upvotes: 62,
    downvotes: 1,
    userVote: 'down',
    saved: true,
  },
  {
    id: 'event5',
    title: 'Spring Game Day',
    description: 'Join us for a day of games, food, and fun! All students welcome.',
    organizerId: 'org3',
    organizerName: 'Stanford Kappa Sigma',
    organizerImageUrl: 'https://logo.clearbit.com/stanford.edu',
    location: 'Main Quad',
    dateTime: '2023-05-27T14:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-c70f1b34e2e7',
    category: 'Recreation',
    isPrivate: false,
    upvotes: 94,
    downvotes: 7,
    userVote: 'up',
    saved: false,
  },
];

// Mock comments
export const mockComments: Comment[] = [
  {
    id: 'comment1',
    eventId: 'event1',
    userId: 'user1',
    username: 'aaronjin',
    userImageUrl: 'https://randomuser.me/api/portraits/lego/1.jpg',
    text: 'Looking forward to this! Will there be vegetarian options?',
    createdAt: '2023-05-10T14:23:00Z',
    upvotes: 15,
    downvotes: 0,
    userVote: null,
  },
  {
    id: 'comment2',
    eventId: 'event1',
    userId: 'org1',
    username: 'stanfordeats',
    userImageUrl: 'https://logo.clearbit.com/stanford.edu',
    text: 'Yes, we will have vegetarian and vegan options available!',
    createdAt: '2023-05-10T15:45:00Z',
    upvotes: 8,
    downvotes: 0,
    userVote: 'up',
  },
  {
    id: 'comment3',
    eventId: 'event2',
    userId: 'user1',
    username: 'aaronjin',
    userImageUrl: 'https://randomuser.me/api/portraits/lego/1.jpg',
    text: 'Excited for this year\'s concert! Last year was amazing.',
    createdAt: '2023-05-12T10:15:00Z',
    upvotes: 6,
    downvotes: 1,
    userVote: null,
  },
]; 